Naive bayes theorem uses bayes theorm for conditional probability with a naive assumption that the features are not correlated to each other and tries to find conditional probability of target variable given the probabilities of features. We will use titanic survival dataset here and using naive bayes classifier find out the survival probability of titanic travellers. We use sklearn library and python for this beginners machine learning tutorial. GaussianNB is the classifier we use to train our model.

#Titanic Survival

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("titanic.csv")
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [ ]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [ ]:
inputs = df.drop('Survived',axis='columns')
target = df.Survived

In [ ]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head(3)

   female  male
0       0     1
1       1     0
2       1     0

In [ ]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

   Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0

In [ ]:
inputs.drop('Sex',axis='columns',inplace=True)
inputs.head(3)

   Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0

In [ ]:
inputs.drop('male',axis='columns',inplace=True)
inputs.head(3)

   Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1

In [ ]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [ ]:
inputs.Age[:10]

#first 10 values

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [ ]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head(6)

   Pclass        Age     Fare  female
0       3  22.000000   7.2500       0
1       1  38.000000  71.2833       1
2       3  26.000000   7.9250       1
3       1  35.000000  53.1000       1
4       3  35.000000   8.0500       0
5       3  29.699118   8.4583       0

In [ ]:
inputs.Age.mean()

29.69911764705882

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.2)

In [ ]:
len(X_train)

712

In [ ]:
len(X_test)

179

In [ ]:
len(inputs)

#total instances

891

In [ ]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [ ]:
model.fit(X_train,y_train)

GaussianNB()

In [ ]:
model.score(X_test,y_test)

0.7653631284916201

In [ ]:
X_test[0:10]

     Pclass        Age     Fare  female
606       3  30.000000   7.8958       0
790       3  29.699118   7.7500       0
74        3  32.000000  56.4958       0
551       2  27.000000  26.0000       0
864       2  24.000000  13.0000       0
376       3  22.000000   7.2500       1
358       3  29.699118   7.8792       1
547       2  29.699118  13.8625       0
362       3  45.000000  14.4542       1
467       1  56.000000  26.5500       0

In [ ]:
y_test[0:10]

606    0
790    0
74     1
551    0
864    0
376    1
358    1
547    1
362    0
467    0
Name: Survived, dtype: int64

In [ ]:
model.predict(X_test[0:10])

array([0, 0, 0, 0, 0, 1, 1, 0, 1, 0])

In [ ]:
model.predict_proba(X_test[:10])

array([[0.9680227 , 0.0319773 ],
       [0.96790872, 0.03209128],
       [0.94361622, 0.05638378],
       [0.92248895, 0.07751105],
       [0.9230994 , 0.0769006 ],
       [0.39274543, 0.60725457],
       [0.42292374, 0.57707626],
       [0.92879597, 0.07120403],
       [0.42793105, 0.57206895],
       [0.73702394, 0.26297606]])

#Email Spam Detector

Here we will build email spam classifier using naive bayes algorithm. We will use sklearn CountVectorizer to convert email text into a matrix of numbers and then use sklearn MultinomialNB classifier to train our model. The model score
with this approach comes out to be very high (around 98%). Sklearn pipeline allows us to handle pre processing transformations easily with its convenient api.

In [2]:
import pandas as pd
df=pd.read_csv("spam.csv")
df

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [3]:
df.groupby('Category').describe()

         Message                                                            \
           count unique                                                top
Category
ham         4825   4516                             Sorry, I'll call later
spam         747    641  Please call our customer service representativ...


         freq
Category
ham        30
spam        4

In [4]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message,df.spam, test_size=0.25)

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [7]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [8]:
emails = [
    'Hey mohan, can we get together to watch football game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [9]:
X_test_count = v.transform(X_test)
model.score(X_test_count, y_test)

0.9870782483847811

Sklearn Pipeline

In [10]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [11]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [12]:
clf.score(X_test,y_test)

0.9870782483847811

In [13]:
clf.predict(emails)

array([0, 1])